"""
@ Author - Krishnabhashkar jha
@ Creation date - 25/03/2020
@ Description - Contains all team members credentials.
"""

adatar = ".//*[contains(text(),'Adatar')]"
sadake = ".//*[contains(text(),'Sadake')]"
apawar2 = ".//*[contains(text(),'Apawar2')]"
ainamdar = ".//*[contains(text(),'Ainamdar')]"
AjayChoudhary = ".//*[contains(text(),'Ajay Choudhary')]"
mkamble = ".//*[contains(text(),'Mkamble')]"
averma = ".//*[contains(text(),'Averma')]"
amane = ".//*[contains(text(),'Amane')]"
srathore = ".//*[contains(text(),'Srathore')]"
nmahala = ".//*[contains(text(),'Nmahala')]"
sswami = ".//*[contains(text(),'Sswami')]"
rchoudhari = ".//*[contains(text(),'Rchoudhari')]"
vtemkar = ".//*[contains(text(),'Vtemkar')]"
asarode = ".//*[contains(text(),'Asarode')]"
rkute = ".//*[contains(text(),'Rkute')]"
pshende = ".//*[contains(text(),'Pshende')]"
njalkote = ".//*[contains(text(),'Njalkote')]"
syadav = ".//*[contains(text(),'Syadav')]"
ssharma = ".//*[contains(text(),'Ssharma')]"
rsingh = ".//*[contains(text(),'Rsingh')]"
praut = ".//*[contains(text(),'Praut')]"
sjakkanawar = ".//*[contains(text(),'Sjakkanawar')]"
smishra2 = ".//*[contains(text(),'Smishra2')]"
vsingh = ".//*[contains(text(),'Vsingh')]"
ymaurya = ".//*[contains(text(),'Ymaurya')]"
skumari2 = ".//*[contains(text(),'Skumari2')]"
ktiwari = ".//*[contains(text(),'Ktiwari')]"
agurav = ".//*[contains(text(),'Agurav')]"
sshetty = ".//*[contains(text(),'Sshetty')]"
gpawar3 = ".//*[contains(text(),'Gpawar3')]"
udhotre = ".//*[contains(text(),'Udhotre')]"
asalunkhe = ".//*[contains(text(),'Asalunkhe')]"
ashinde = ".//*[contains(text(),'Ashinde')]"

